### ISSUE TITLE
librato-node should let you use it more transactionally

### ISSUE THREAD

**Issue by vincentwoo** [goodeggs/librato-node#15]
Right now the only blessed use case is to start the worker and hope for the best. I would like to be able to (in a short-lived node script):

1. Not start the worker
2. Gather some data via `librato.timing(...)`
3. Call `librato.flush` with a callback that tells me when the data has been written to Librato, so that I can terminate the process.

Any chance you guys would be down for exposing `librato.flush`'s callback?

**Comment by bobzoller** [comment]
sounds good.  PR welcome!
