### ISSUE TITLE
process.once('exit', function() {librato.stop(); }) is unsafe.

### ISSUE THREAD

**Issue by timlesallen** [goodeggs/librato-node#18]
According to http://nodejs.org/api/process.html#process_event_exit, only synchronous handlers registered with this event are safe.  However unless I am mistaken the sending of data to librato is async.  We need a callback on the `librato.stop()` method so we can be sure it's happened, and we need to not tie it to the `exit` event (as is shown in the code example in the README). :)

**Comment by mseest** [comment]
Is there any solutions for this one?

**Comment by bobzoller** [comment]
@adborden added the callback to stop (and flush) in #21, and I just tagged and published v1.3.0 which includes that change.

@timlesallen is right that async isn't safe from `exit`... my example was overly simplified.  How about I change the README to use `SIGINT` instead.  It still wouldn't demonstrate giving stop a callback, but would be _more_ correct.
