### ISSUE TITLE
Control the resolution/period 

### ISSUE THREAD

**Issue by juddernaught** [goodeggs/librato-node#20]
Currently, it updates librato every 60 seconds. Is there any way to update librato at other intervals such as 1 second or 5 seconds? This value is set in worker.coffee, is there anway to set some config value for librato to modify this value?

**Comment by kevinburkeshyp** [comment]
Fixed by #30

**Comment by kevinburkeshyp** [comment]
This can be closed

**Comment by bobzoller** [comment]
thanks!
