### ISSUE TITLE
Is there a way to publish statistics that aren't counters or durations?

### ISSUE THREAD

**Issue by demands** [goodeggs/librato-node#25]
Say, for example, I am doing an operation that affects users, and I'd like to have a graph of the number of users affected each time the operation runs. Can I do this with librato-node? *Should* I be able to do this?

**Comment by bobzoller** [comment]
totally.  `measure` and `timing` are actually the same implementation, and they handle arbitrary numbers exactly the same as durations.

```coffee-script
librato.measure 'mailchimp.removed', 5
```
