### ISSUE TITLE
Counters are being recorded as gauges

### ISSUE THREAD

**Issue by garnold** [goodeggs/librato-node#36]
Heyo!  I'm recording/sending 2 metrics to Librato, one using `#measure` (gauge) and the other using `#increment` (counter), however both are being recorded as gauges in Librato:

![screenshot 2015-04-10 15 59 24](https://cloud.githubusercontent.com/assets/83754/7097402/e58d07ca-df9a-11e4-9188-f30195a9c41d.png)

I believe this is because the `librato.flush` method in `librato.coffee` is not properly classifying metrics as counters and gauges, as required by the Librato API:

http://dev.librato.com/v1/post/metrics

**Comment by bobzoller** [comment]
The original ruby library I ported to node also represented increments as gauges... this is why things are the way they are.  PR #27 switches increment to use counters, and just needs a tiny bit of love to get merged.

I have a few minutes... I'll see if I can't tackle it now, but I'll close this and you can watch #27.

**Comment by garnold** [comment]
Thanks @bobzoller . I've temporarily moved to [librato-metrics](https://www.npmjs.com/package/librato-metrics) while the counter issue here is sorted out.
