### ISSUE TITLE
Obscured error messages from librato

### ISSUE THREAD

**Issue by demands** [goodeggs/librato-node#42]
Librato is unhappy with the messages it's getting from librato-node, but the only error message I see is:

```
Error sending to Librato: { errors: { params: { type: [Object] } }, request_time: 1436215860 } (statusCode: 400)
```

It would be really helpful to see what `errors.params.type` really is, so I could diagnose the issue.
Thanks :)

**Comment by kevinburkeshyp** [comment]
believe this is a `console.log` issue right? it only prints 2 levels of objects. i believe `util.inspect` can print more levels worth of objects if you pass the right args to it.
