### ISSUE TITLE
Set a timeout on librato requests

### ISSUE THREAD

**Issue by kevinburkeshyp** [goodeggs/librato-node#47]
any idea how quickly librato usually responds? would be great to set a timeout of 10s or so and fail earlier if the connection can't be established or the server doesn't respond.

**Comment by Jerskouille** [comment]
Seems to be answered with https://github.com/goodeggs/librato-node#request-options ? (I know, 2 years later, but still :) )

**Comment by bobzoller** [comment]
thanks @Jerskouille, you're right.
