### ISSUE TITLE
getting a lot of timed out errors

### ISSUE THREAD

**Issue by vincentwoo** [goodeggs/librato-node#51]
`{"level":"error","message":"librato error: { [Error: connect ETIMEDOUT 107.21.215.21:443]\n  code: 'ETIMEDOUT',\n  errno: 'ETIMEDOUT',\n  syscall: 'connect',\n  address: '107.21.215.21',\n  port: 443 }","timestamp":"2016-08-31T23:00:19.623Z"}`

Anyone else seeing this?

**Comment by josephruscio** [comment]
[Librato here] @mbeale does this correlate with the other reports you were investigating earlier today?

**Comment by vincentwoo** [comment]
yeah, figure it was probably on the server end

**Comment by mbeale** [comment]
We are still investigating. I will reach out privately when i have new information.

**Comment by bobzoller** [comment]
closing
